title: Project

files:
  sortable: true

pages: false

fields:
  title:
    label: Title
    type:  text
    width: 2/4

  year:
    label: Year
    type:  text
    width: 1/4

  category:
    label: Category
    type:  text
    width: 1/4

  text:
    label: Text
    type:  textarea
